const SET_LIST_FILM = 'SET_LIST_FILM'
const SET_LIST_FILM_NOW_SHOWING = 'SET_LIST_FILM_NOW_SHOWING'
const SET_LIST_FILM_COMING_SOON = 'SET_LIST_FILM_COMING_SOON'
const SET_SHOWTIMES = 'SET_SHOWTIMES'
export { SET_LIST_FILM, SET_LIST_FILM_NOW_SHOWING, SET_LIST_FILM_COMING_SOON,SET_SHOWTIMES }