const SET_CINEMA_ROOM_INFO = 'SET_CINEMA_ROOM_INFO'
const SET_BOOKING_SEATS = 'SET_BOOKING_SEATS'
const SET_TICKETS_LIST = 'SET_TICKETS_LIST'
const SET_OTHER_USER_BOOKING  = 'SET_OTHER_USER_BOOKING '
const RESET_BOOKING_SEATS = 'RESET_BOOKING_SEATS'
export {SET_CINEMA_ROOM_INFO,SET_BOOKING_SEATS,SET_TICKETS_LIST,RESET_BOOKING_SEATS,SET_OTHER_USER_BOOKING}