const SET_USER_LOGIN = 'SET_USER_LOGIN'
const SET_USER_ACCOUNT_INFO = 'SET_USER_ACCOUNT_INFO'
const SET_USER_LIST = 'SET_USER_LIST';
const SET_USER_LIST_PAGNINATION = 'SET_USER_LIST_PAGNINATION';
const SET_USERS_PER_PAGE = 'SET_USERS_PER_PAGE'
const SET_USER_TYPE = 'SET_USER_TYPE'
const SET_USER_INFO = 'SET_USER_INFO' // DÙNG CHO API CẬP NHẬP VÀ CHÌNH SỬA THÔNG TIN NGƯỜI DÙNG 
const SET_TITLE_EDIT_USER = 'Chỉnh Sửa Thông Tin Người Dùng'
const SET_TITLE_ADD_USER = 'Thêm Người Dùng'
export {
    SET_USER_LOGIN, SET_USER_ACCOUNT_INFO, SET_USER_LIST,
    SET_USER_LIST_PAGNINATION, SET_USERS_PER_PAGE, SET_USER_TYPE, SET_USER_INFO,
    SET_TITLE_ADD_USER, SET_TITLE_EDIT_USER
}